### ISSUE TITLE
Failed to fetch the Google Scholar page

### ISSUE THREAD

**Issue by kaichengyang0828** [ChenLiu-1996/CitationMap#3]
Hi, I get the error:Exception: Failed to fetch the Google Scholar page, and I confirm that the Google Scholar ID is correct. Do you have any suggestions?

**Comment by ChenLiu-1996** [comment]
Hi @Kaicheng-Yang0828,

This is probably caused by `MaxTriesExceededException` (you can verify in the error message), which is likely because Google Scholar suspects you and starts blocking you.

While I was developing this tool, the thing that helped me the most is my University VPN. I disconnect and reconnect every time I get blocked by Google Scholar.

For more details, you can read on the [Debug](https://github.com/ChenLiu-1996/CitationMap?tab=readme-ov-file#debug) section.

**Comment by ChenLiu-1996** [comment]
I am not very sure if this will help you. Google Scholar blocking is indeed one of the biggest challenges for this tool.

**Comment by changyeli** [comment]
It happened to me as well - deleting the cache folder located in the script helped to update the map.
